function get(city)
  data = http.get("http://worldtimeapi.org/api/timezone/Europe/"..city..".txt")
  abbreviation = string.sub(data.readLine(), 14)
  client_ip = string.sub(data.readLine(), 11)
  datetime = string.sub(data.readLine(), 10)
  day_of_week = string.sub(data.readLine(), 13)
  day_of_year = string.sub(data.readLine(), 13)
  dst = string.sub(data.readLine(), 5)
  dst_from = string.sub(data.readLine(), 10)
  dst_offset = string.sub(data.readLine(), 12)
  dst_until = string.sub(data.readLine(), 11)
  raw_offset = string.sub(data.readLine(), 12)
  timezone = string.sub(data.readLine(), 10)
  unixtime = string.sub(data.readLine(), 10)
  utc_datetime = string.sub(data.readLine(), 14)
  utc_offset = string.sub(data.readLine(), 12)
  week_number = string.sub(data.readLine(), 13)
  data.close()
  return abbreviation, client_ip, datetime, day_of_week, day_of_year, dst, dst_from, dst_offset, dst_until, raw_offset, timezone, unixtime, utc_datetime, utc_offset, week_number
end